### ISSUE TITLE
Using Fits file as input raise Pyxis issue when simulating.

### ISSUE THREAD

**Issue by JulienNGirard** [ska-sa/rodrigues#69]
Reference crashed job can be found on rodrigues.meqtrees.net under Job #9: "fits file reproduce pyxis error".

Input fits file is "astronomical compliant" in terms of axes, cellsize etc.
[M31_256.fits.zip](https://github.com/ska-sa/rodrigues/files/606509/M31_256.fits.zip)
(M31 is one of the mostly used sky model when imagers are compared).

Pyxis is complaining about a missing predict_vis module when fits images are used. I tried to look and correct for it by shunting skymodels, on an offline version of pyxis but ended to think that either I am using the web form badly or something was not implemented somewhere in RODRIGUES.

The crashing log:
> running...
> #!/bin/bash -ve
> 
> pyxis CFG=/parameters.json OUTFILE=/output/results OUTDIR=/output azishe
> Traceback (most recent call last):
> File "/usr/bin/pyxis", line 298, in <module>
> Pyxis.Internals.run(*commands);
> File "/usr/lib/python2.7/dist-packages/Pyxis/Internals.py", line 1102, in run
> comcall();
> File "./pyxis-ckat.py", line 192, in azishe
> simsky(lsmname=skymodel,noise=0 if katalog else noise,addToCol='CORRECTED_DATA')
> File "./pyxis-ckat.py", line 42, in simsky
> im.argo.predict_vis(lsmname, wprojplanes=128, column=_column)
> AttributeError: 'module' object has no attribute 'predict_vis'
> 2016/11/22 13:36:26 PYXIS: ===[ Pyxis: Python eXtensions for Inteferometry Scripting (C) 2013 by Oleg Smirnov <oms@ska.ac.za> ]===
> 2016/11/22 13:36:26 PYXIS: VERBOSE=1 by default
> 2016/11/22 13:36:26 PYXIS: loading Pyxis into context '__main__'
> 2016/11/22 13:36:26 PYXIS: auto-loading from .: pyxis-ckat.py pyxis-ckat.conf
> 2016/11/22 13:36:26 PYXIS: registered module 'std'
> 2016/11/22 13:36:26 PYXIS: registered module 'im'
> 2016/11/22 13:36:26 PYXIS: registered module 'im.argo'
> 2016/11/22 13:36:26 PYXIS: registered module 'im.argo'
> 2016/11/22 13:36:26 PYXIS: registered module 'ms'
> 2016/11/22 13:36:26 PYXIS: registered module 'mqt'
> 2016/11/22 13:36:26 PYXIS: registered module 'imager'
> 2016/11/22 13:36:26 PYXIS: registered module 'lsm'
> 2016/11/22 13:36:26 INFO: redirecting log output to ./log-ska1sims.txt
> 2016/11/22 13:36:26 PYXIS: running command CFG=/parameters.json
> 2016/11/22 13:36:26 PYXIS: running command OUTFILE=/output/results
> 2016/11/22 13:36:26 PYXIS: running command OUTDIR=/output
> 2016/11/22 13:36:26 INFO: redirecting log output to /output/log-ska1sims.txt
> 2016/11/22 13:36:26 PYXIS: running command azishe
> 2016/11/22 13:36:40 INFO: rodrigues1479821786.867836.MS ddid 0 is spwid 0, 1 channels, centred on 700.0 MHz, bandwidth 50.0 MHz
> 2016/11/22 13:36:41 INFO: max baseline is 7.696 km
> 2016/11/22 13:36:41 INFO: saved UV coverage plot to /output/results-uvcov.png
> 2016/11/22 13:36:41 INFO: >>> rodrigues1479821786.867836.MS freq 700.00 MHz (lambda=0.43m), bandwidth 5e+04 kHz, 10.00s integrations, 0.25h synthesis
> 2016/11/22 13:36:41 INFO: >>> SEFD of 831.00 Jy gives per-visibility noise of 26.28 mJy
> 2016/11/22 13:36:41 PYXIS: executing 'tigger-convert --select="r<0.500000deg" --select="I<1.000000" --select="I>0.001000" --recenter=J2000,0h0m0s,-30d0m0s katalog/nvss6deg.lsm.html /output/rodrigues1479821786.867836.lsm.html -f':
> 2016/11/22 13:36:43 PYXIS: 'tigger-convert --select="r<0.500000deg" --select="I<1.000000" --select="I>0.001000" --recenter=J2000,0h0m0s,-30d0m0s katalog/nvss6deg.lsm.html /output/rodrigues1479821786.867836.lsm.html -f' succeeded
> 2016/11/22 13:36:43 PYXIS: executing '/usr/bin/time meqtree-pipeliner.py --mt 6 -c tdlconf.profiles [turbo-sim:custom] ms_sel.msname=rodrigues1479821786.867836.MS ms_sel.ddid_index=0 ms_sel.field_index=0 tiggerlsm.filename=/output/rodrigues1479821786.867836.lsm.html noise_stddev=0.026278527356 ms_sel.output_column=CORRECTED_DATA /usr/lib/python2.7/dist-packages/Cattery/Siamese/turbo-sim.py =_tdl_job_1_simulate_MS':
> 2016/11/22 13:37:18 PYXIS: meqtree-pipeliner.py succeeded
> 2016/11/22 13:37:18 ERROR: Exception raised, aborting
> 2016/11/22 13:37:18 ERROR: Exception raised, aborting
> 2016/11/22 13:37:18 ERROR: exiting with error code 1, check the logs for errors
> 2016/11/22 13:37:18 INFO: last logfile was /output/log-ska1sims.txt
> 2016/11/22 13:37:18 INFO: elapsed time is 0h0m51.28s
> simulation crashed (state 1)

thank you

**Comment by gijzelaerr** [comment]
@SpheMakh what do you think of this? API mismatch?

**Comment by SpheMakh** [comment]
The simulator image has an old version of pyxis.

**Comment by SpheMakh** [comment]
I'll update the Dockerfile.

**Comment by gijzelaerr** [comment]
ok. can you fix the versions of the requirements or stick to KERN-1? That would prevent this kind of problems.

**Comment by gijzelaerr** [comment]
I think this has been fixed now by updating the container and basing it on KERN-1.

**Comment by JulienNGirard** [comment]
Hello and thank you. I tried to test it on rodrigues.meqtrees.net but I think it's still running the old version.
I am going to test it offline, but an update of rodrigues.meqtrees.net, would let us know quicker if it worked.

**Comment by gijzelaerr** [comment]
hi julien,

I forgot to tell you that you should use the container with the 'kern' tag:

http://rodrigues.meqtrees.net/scheduler/job/create/4/

**Comment by JulienNGirard** [comment]
ok thanks

Julien

**Comment by JulienNGirard** [comment]
I tried with both "Kern" tag and "latest" tag of the radioastro/simulator, and I still have the same error:
To me, it is just not implemented in pyxis. I can try to code it myself to make it compatible with Fits file but that is weird anyways.

> running...
> #!/bin/bash -ve
> 
> pyxis CFG=/parameters.json OUTFILE=/output/results OUTDIR=/output azishe
> Traceback (most recent call last):
> File "/usr/bin/pyxis", line 298, in <module>
> Pyxis.Internals.run(*commands);
> File "/usr/lib/python2.7/dist-packages/Pyxis/Internals.py", line 1102, in run
> comcall();
> File "./pyxis-ckat.py", line 192, in azishe
> simsky(lsmname=skymodel,noise=0 if katalog else noise,addToCol='CORRECTED_DATA')
> File "./pyxis-ckat.py", line 42, in simsky
> im.argo.predict_vis(lsmname, wprojplanes=128, column=_column)
> AttributeError: 'module' object has no attribute 'predict_vis'
> 2016/12/07 10:14:52 PYXIS: ===[ Pyxis: Python eXtensions for Inteferometry Scripting (C) 2013 by Oleg Smirnov <oms@ska.ac.za> ]===

**Comment by gijzelaerr** [comment]
@SpheMakh can you elaborate.

**Comment by gijzelaerr** [comment]
@SpheMakh says it is too much work to fix the simulator, he recommends not to use a fits file but a text file. here is an example simulation:

http://rodrigues.meqtrees.net/viewer/15/overview/

**Comment by JulienNGirard** [comment]
ok... I'll go for that. Thanks
Cheers.

**Comment by rdeane** [comment]
This would be unfortunate for using RODRIGUES for MeqSilhouette in the long
run as most synthetic data generation inputs are small FITS images (time
variable and full Stokes). The example referenced in the above message has
a null sky model, could someone perhaps provide an example of the format of
such a file so we can make the appropriate parser script in future?
Presumably the FITS header info is simply repeated.

cheers
Roger

**Comment by SpheMakh** [comment]
@rdeane This is a problem for the simulator container only. RODRIGUES itself is not affected by this.

**Comment by rdeane** [comment]
ah ok, great.

On 14 December 2016 at 10:19, Sphesihle Makhathini <notifications@github.com
